"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
[opener]
vscode = [{ run = '"code" %s', desc = "Open with VS Code", orphan = true, for = "unix"}]
[open]
prepend_rules = [
    # Folder
    { mime = "inode/directory", use = ["open", "vscode", "edit", "reveal" ] },
    # Text
    { mime = "text/*", use = [ "edit", "vscode", "reveal" ] },
    # Image
    { mime = "image/*", use = [ "open", "reveal" ] },
    # Media
    { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
    # JSON
    { mime = "application/{json,ndjson}", use = [ "edit", "vscode", "reveal" ] },
    { mime = "*/javascript", use = [ "edit", "vscode", "reveal" ] },
    # Empty file
    { mime = "inode/empty", use = [ "edit", "vscode", "reveal" ] },
    # Virtual file system
    { mime = "vfs/{absent,stale}", use = "download" },
    # Fallback
    { url = "*", use = [ "open", "vscode", "reveal" ] },
]
