{ ... }:
{
  homebrew = {
    enable = true;
    caskArgs.no_quarantine = true;
    global.brewfile = true;
    onActivation.cleanup = "zap";
    masApps = {
      "Windows App" = 1295203466;
      "Yubico Authenticator" = 1497506650;
    };
    casks = [
      "1password"
      "1password-cli"
      "blender"
      "brave-browser"
      "devpod"
      "discord"
      "drawio"
      "firefox"
      "hoppscotch"
      "iina"
      "iterm2"
      "keycastr"
      "losslesscut"
      "mac-mouse-fix"
      "mactex"
      "microsoft-auto-update"
      "microsoft-excel"
      "microsoft-outlook"
      "microsoft-powerpoint"
      "microsoft-teams"
      "microsoft-word"
      "nikitabobko/tap/aerospace"
      "obs"
      "obsidian"
      "onedrive"
      "orbstack"
      "podman-desktop"
      "qlmarkdown"
      "raycast"
      "signal"
      "slack"
      "syntax-highlight"
      "telegram-desktop"
      "threema"
      "typora"
      "ukelele"
      "visual-studio-code"
      "vmware-fusion"
      "whatsapp"
      "wireshark-app"
      "zed"
      # "4k-video-downloader"
      # "adobe-acrobat-reader"
      # "alt-tab"
      # "balenaetcher"
      # "jetbrains-toolbox"
      # "logitech-presentation"
      # "ollama"
      # "plex"
      # "qflipper"
      # "the-unarchiver"
      # "thunderbird"
      # "ukelele"
      # "visual-studio"
    ];
    taps = [
      "anchore/grype"
      "argoproj/tap"
      "dagger/tap"
      "fluxcd/tap"
      "go-task/tap"
      "goreleaser/tap"
      "hashicorp/tap"
      "nikitabobko/tap"
      "powershell/tap"
      "rest-sh/tap"
      "siderolabs/tap"
    ];
    brews = [
      "argocd"
      "argoproj/tap/kubectl-argo-rollouts"
      "blueutil"
      "broot"
      "btop"
      "cilium-cli"
      "clusterctl"
      "crane"
      "dagger/tap/dagger"
      "difftastic"
      "dive"
      "dua-cli"
      "entr"
      "fclones"
      "fd"
      "ffmpeg"
      "fluxcd/tap/flux"
      "gdu"
      "gitleaks"
      "gnmic"
      "go-task/tap/go-task"
      "golangci-lint"
      "goreleaser/tap/goreleaser"
      "graphviz"
      "grype"
      "hadolint"
      "hashicorp/tap/packer"
      "hubble"
      "imagemagick"
      "ingress2gateway"
      "iproute2mac"
      "istioctl"
      "k9s"
      "ko"
      "kompose"
      "krew"
      "kubent"
      "mas"
      "mtr"
      "ncdu"
      "nmap"
      "nnn"
      "node"
      "opentofu"
      "pandoc"
      "powershell/tap/powershell"
      "protobuf"
      "rdfind"
      "rest-sh/tap/restish"
      "ripgrep"
      "ripgrep-all"
      "sevenzip"
      "siderolabs/tap/talosctl"
      "superfile"
      "syft"
      "telnet"
      "terraform"
      "terraform-docs"
      "terragrunt"
      "tfmigrate"
      "tio"
      "tldr"
      "tree"
      "trivy"
      "typst"
      "uv"
      "yarn"
      "yq"
      # "apktool"
      # "cmatrix"
      # "htop"
      # "iodine"
      # "jadx"
      # "pnpm"
      # "rust"
      # "termshark"
      # "tesseract"
    ];
  };
}
