{ lib, ... }:
{
  homebrew = {
    enable = true;
    caskArgs.no_quarantine = true;
    global.brewfile = true;
    onActivation.cleanup = "zap";
    onActivation.extraFlags = [
      # "--force-cleanup"
      # "--zap"
    ];
    masApps = {
      "Windows App" = 1295203466;
      "Yubico Authenticator" = 1497506650;
      "WireGuard" = 1451685025;
    };
    casks = [
      "1password"
      "1password-cli"
      "Untersander/tap/explorer"
      "blender"
      "brave-browser"
      "devpod"
      "discord"
      "drawio"
      "firefox"
      "go-task/tap/go-task"
      "google-chrome"
      "goreleaser/tap/goreleaser"
      "handbrake-app"
      "iina"
      "iterm2"
      "keycastr"
      "kopiaui"
      "losslesscut"
      "mac-mouse-fix"
      "mactex"
      "microsoft-auto-update"
      "microsoft-excel"
      "microsoft-outlook"
      "microsoft-powerpoint"
      "microsoft-teams"
      "microsoft-word"
      "nextcloud"
      "nikitabobko/tap/aerospace"
      "obs"
      "obsidian"
      "onedrive"
      "orbstack"
      "podman-desktop"
      "powershell"
      "qlmarkdown"
      "raycast"
      "signal"
      "slack"
      "syntax-highlight"
      "telegram-desktop"
      "threema@beta"
      "typora"
      "ukelele"
      "utm"
      "visual-studio-code"
      "webex"
      "whatsapp"
      "zed"
      # "4k-video-downloader"
      # "adobe-acrobat-reader"
      # "alt-tab"
      # "balenaetcher"
      # "hoppscotch"
      # "jetbrains-toolbox"
      # "logitech-presentation"
      # "ollama"
      # "plex"
      # "qflipper"
      # "the-unarchiver"
      # "thunderbird"
      # "visual-studio"
    ];
    taps =
      lib.map
        (tap: {
          name = tap;
          trusted = true;
          force_auto_update = true;
        })
        [
          "Untersander/tap"
          "anchore/grype"
          "anomalyco/tap"
          "argoproj/tap"
          "dagger/tap"
          "felixKratz/formulae"
          "fluxcd/tap"
          "go-task/tap"
          "goreleaser/tap"
          "handfish/tap"
          "hashicorp/tap"
          "nikitabobko/tap"
          "rest-sh/tap"
          "siderolabs/tap"
        ];
    brews = [
      "anomalyco/tap/opencode"
      "argocd"
      "argoproj/tap/kubectl-argo-rollouts"
      "blueutil"
      # "broot"
      "cilium-cli"
      "clusterctl"
      "cmctl"
      "crane"
      "dagger/tap/dagger"
      "difftastic"
      "dive"
      "dua-cli"
      "entr"
      "egctl"
      "fclones"
      "fd"
      "felixKratz/formulae/borders"
      "ffmpeg"
      "fluxcd/tap/flux"
      "gitleaks"
      "gnmic"
      "go"
      "golangci-lint"
      "graphviz"
      "grype"
      "hadolint"
      "handfish/tap/talos-pilot"
      "hashicorp/tap/packer"
      # "helm"
      "hubble"
      "imagemagick"
      "ingress2gateway"
      "iproute2mac"
      "istioctl"
      "k9s"
      "ko"
      "kopia"
      "kompose"
      "kubent"
      "mas"
      "mtr"
      "ncdu" # graphic du
      "nnn" # terminal file browser
      "opentofu"
      "pandoc"
      "podman"
      "protobuf"
      "rdfind"
      "sevenzip"
      "siderolabs/tap/talosctl"
      "syft"
      "telnet"
      "terraform"
      "terraform-docs"
      "terragrunt"
      "tfmigrate"
      "tio"
      "tree"
      "trivy"
      "typst"
      "uv"
      "yarn"
      "yq"
      # "apktool"
      # "cmatrix"
      # "htop"
      # "iodine"
      # "jadx"
      # "pnpm"
      # "rest-sh/tap/restish"
      # "rust"
      # "termshark"
      # "tesseract"
    ];
  };
}
